// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Cbtlog struct {
	ID                 int64
	FilePath           string
	Url                sql.NullString
	UploadStatus       string
	UploadStatusReason string
	Active             int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
