// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Upload struct {
	ID           int64
	FilePath     string
	Url          sql.NullString
	Status       string
	StatusReason sql.NullString
	Active       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
