// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package database

import (
	"context"
	"database/sql"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (file_path, url) VALUES (?, ?) RETURNING id, file_path, url, status, status_reason, active, created_at, updated_at
`

type CreateUploadParams struct {
	FilePath string
	Url      sql.NullString
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createUpload, arg.FilePath, arg.Url)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Url,
		&i.Status,
		&i.StatusReason,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
